

GET http://localhost:3101/users
content-type: application/json
###

GET http://localhost:3101/users/11
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYXNzQG1haWwuY29tIiwic3ViIjoxMSwicm9sZXMiOlsiYWRtaW4iLCJvd25lciIsInN1cGVydXNlciJdLCJhY3RpdmUiOjEsImZpbyI6IkdyYXNzIEhvcHBlciIsImlhdCI6MTc0NjQ1NjU1NiwiZXhwIjoxNzQ2NDYwMTU2fQ.YouzMzN0f7zpxlbwTovf9BlT43F9OxQGsH7UVT-TUq4
###

POST http://localhost:3101/users/mail
content-type: application/json

{
	"email": "grass@rambler.ru"
}
###
POST http://localhost:3101/users/token
content-type: application/json

{
	"id": 1,
	"token": "d1a3b4c5-6e7f-4a89-9b0c-d1e2f3a4b5c6"
}
###

POST http://localhost:3101/users/update
content-type: application/json

{
	"id": 14,
    "login": "guest",
    "password": "guest",
    "fio": "Guest",
    "email": "guest@mail.com",
    "token": "23wd4tg23qw42dd34",
    "salt": 2323232,
    "token_expare": 128,
    "roles": [
      "guest"
    ],
    "active": 1
}
###
POST http://localhost:3101/users
content-type: application/json

{
	"fio": "Ollama Bot",
	"login": "ollama",
	"password": "ollama",
	"email":"ollama@mail.ru",
	"token": "qqw12yw45qwe",
	"salt": 8053334,
	"token_expare": 12,
	"roles": [
		"bot"
		],
	"active": 1
}
###

GET https://api.randomdatatools.ru/?typeName=true&typeName=all&params=FirstName,LastName,FatherName,Email
# GET https://api.randomdatatools.ru/?typeName=true&typeName=all
content-type: application/json
###

DELETE http://localhost:3000/users/88
content-type: application/json
###

# -------------- Auth ---------------

POST http://localhost:3101/auth/login
content-type: application/json

{
	"name": "grass@mail.com",
	"pass": "grass"
}
###

GET http://localhost:3101/auth/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6ImdyYXNzQG1haWwuY29tIiwicm9sZXMiOlsiYWRtaW4iLCJvd25lciIsInN1cGVydXNlciJdLCJhY3RpdmUiOjEsImZpbyI6IkdyYXNzIEhvcHBlciIsImlhdCI6MTc0Nzc1MzA1OSwiZXhwIjoxNzQ3NzU2NjU5fQ._LSlfkJLQitRMiA5x8u8iaWBg5XgMAnILtK3DkH2Skk
###

# -------------- Ollama---------------

POST http://localhost:11434/api/generate
content-type: application/json

{
	"model": "llama3",
	"prompt": "Привет!"
}
###

